name: Trigger auto deployment for user-service

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.USERSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.USERSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.USERSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Instalar extensión de Azure Container App
        run: |
          az extension add --name containerapp --upgrade --yes

      - name: Compilar imagen con Docker local de GitHub
        run: |
          docker build -t user-service-local:${{ github.sha }} .

      - name: Desplegar la imagen directo a la Container App
        run: |
          az containerapp container image set \
            --name user-service \
            --resource-group ecosmart \
            --image user-service-local:${{ github.sha }}