name: Trigger auto deployment for user-service

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🐳 Compilar y subir a Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # REEMPLAZA "TU_USUARIO_DOCKER" con tu usuario real
          tags: josutrres/user-service:latest
          provenance: false

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.USERSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.USERSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.USERSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Instalar extensión de Azure Container App
        run: |
          az extension add --name containerapp --upgrade --yes

      - name: 🚀 Configurar credenciales y actualizar imagen en Azure
        run: |
          
          az containerapp registry set \
            --name user-service \
            --resource-group ecosmart \
            --server docker.io \
            --username "${{ secrets.DOCKER_USERNAME }}" \
            --password "${{ secrets.DOCKER_PASSWORD }}"

          az containerapp update \
            --name user-service \
            --resource-group ecosmart \
            --image docker.io/josutrres/user-service:latest